name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Run Sonar Analysis
    runs-on: ubuntu-latest
    env:
      SONAR_SERVER_URL: "https://sonarcloud.io"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Setup Sonarqube
        run: |
          dotnet tool install --global coverlet.console
          dotnet tool install --global dotnet-sonarscanner
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /o:"tomer-apiiro-test" \
            /k:"tomer-apiiro-test_dotnet-test" \
            /d:sonar.login="$SONAR_TOKEN" \
            /d:sonar.host.url="$SONAR_SERVER_URL" \
            /d:sonar.cs.opencover.reportsPaths=Math.Test/coverage.opencover.xml
          dotnet build
          dotnet test --no-build Math.Test/Math.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"